midudev/jsconf.es

- src/components/Footer.astro
- src/layouts/Layout.astro
- src/pages/index.astro
This PR includes the necessary fixes to improve the user experience across different screen sizes. Below are the changes made to resolve responsive design issues in the affected sections.
---
**LIVE:**  
**NEW:**  
---
**LIVE:**  
**NEW:**  
---
**LIVE:**  
**NEW:**
> Fix Responsive Design

- src/pages/coc.astro
- src/pages/index.astro
Quick fix of a couple of words, like "JSConf México" to "JSConf España".
> Fix grammatical errors

- src/sections/Footer.astro
- src/sections/Header.astro
- The header and footer title were fixed:
> fix: Header and Footer title

- src/components/Hero.astro
- src/sections/Landing.astro
He comenzado la sección del hero para tener una base para ayudar a acelerar esta sección
> feat: Add Hero component and integrate it into the Landing section

- src/components/WorkshopSkillTag.astro
- src/sections/Workshops.astro
Se reorganiza el codigo en estas partes para evitar la marcacion de errores por vscode y un mejor uso en el codigo
> refactor: Reorganizacion de los import en Workshops y definicio de interface en WorkshopSkillTag Component

- src/components/Button.astro
- src/components/Hero.astro
- src/sections/Header.astro
- tsconfig.json
botones con bordes redondeados
> rotacion de bg de la palabra 'exclusiva' de la seccion hero

- src/components/Hero.astro
- src/sections/Footer.astro
-organized the icons of the landing buttons
-added the title in the footer "Diseñado con ❤️ por Vladyslav"
> fix: icons buttons landing and add title in footer

- src/sections/Header.astro
Ajuste del responsive en el header para evitar bugs visuales
Antes:
Despues:
> style: Ajuste del header responsive

- src/components/SpeakerCard.astro
- src/sections/Speakers.astro
-removed extra bracket in SpeakerCard.astro
-added space that requested astro in SpeakerCard.astro
-updated "vue" title to "google" in Speakers.astro
> fix: fixed little things in the speakers

- src/components/Hero.astro
Ajuste en el padding y el underline en la seccion de la phrase
Antes:
Despues:
> style: Ajuste en la seccion de la phrase

- public/jsrace.ics
- src/components/LinkButtonRace.astro
- src/components/RaceToCalendar.astro
- src/sections/RunAndFun.astro
Refactor del <a> en el boton de la seccion de carrera en un componente y agregado del descargable para el recordatorio de la fecha y hora de la carrera
Se usa el mismo metodo que el del evento principal
> feat: Add button to download a reminder of the race

- src/components/AddToCalendarDialog.astro
- src/sections/Header.astro
El event.preventDefault estaba evitando el correcto funcionamiento del handleClick, decidí borrarlo ya que no tenía otra funcion.
https://github.com/user-attachments/assets/22205217-dea2-44ef-837b-e6c65d391ae4
> Fix handleLinkClick in linksMobile

- src/components/Menu.astro
- src/sections/Header.astro
- se separa el componente `Nav` del `Header`
- se agregar un `border-bottom` para identificar el elemento del menú seleccionado
> geekhadev - refactor: add active item nav

- src/sections/Footer.astro
Link actual en el botón tiene href="#" , he modificado este parámetro para que tenga link a la web actual.  
Soy Vladyslav, y el link es verificado.
> feat: add designer mention url to footer href

- pnpm-lock.yaml
- public/robots.txt
- public/sitemap.xml
- src/components/Break.astro
- src/components/Hero.astro
- src/components/LinkButtonRace.astro
- src/components/Menu.astro
- src/components/SpeakerCard.astro
- src/components/Talk.astro
- src/components/WorkshopCard.astro
- src/consts/links.ts
- src/pages/legal.astro
- src/sections/Agenda.astro
- src/sections/Footer.astro
- src/sections/Header.astro
- src/sections/PreEvent.astro
- src/sections/Presenter.astro
- src/sections/RunAndFun.astro
- src/sections/Speakers.astro
- src/sections/Sponsors.astro
- src/sections/WhenAndWhere.astro
- src/sections/Why.astro
- src/sections/Workshops.astro
- tailwind.config.mjs
- tsconfig.json
Antes que nada, ejecuté pnpm format y por eso hay algunos archivos de mas afectados por la feature
Accesibilidad: 
- Alts faltantes
- Aria label en links
- Se corrige color de textos que se mezclaban con el fondo segun lightroom
- Se añade robots.txt y sitemap.xml
- Se corrige orden secuencial de etiquetas de heading.
Performance:
- Se utiliza componente Image recomendado por Astro
- Se le indica width y height inicial a cada Image
> Feat improve performance accessibility

- src/components/SpeakerCard.astro
[Grabación de pantalla 2024-12-19 a la(s) 1.00.13 p. m.webm](https://github.com/user-attachments/assets/d3695be2-c90c-47d0-9b33-17446efb64da)
> efecto hover en speakers cards

- src/components/SpeakerCard.astro
- src/sections/Speakers.astro
Convierte a las card de speakers en un link a su principal red social o página web
> feat: add social media links to speaker cards

- src/components/WhyCard.astro
- src/sections/Why.astro
[glow.webm](https://github.com/user-attachments/assets/4ee3dc2a-8054-42ec-8f02-caa54cee49e3)
> glow hover effect

- src/components/Button.astro
- src/sections/Sponsors.astro
[highlighted buttons.webm](https://github.com/user-attachments/assets/1d80db04-138f-4046-838f-3742ed6d2076)
> highlighted black buttons

- src/sections/Header.astro
This Pull Request adds a link to the header (<a href="#Home">) that redirects users to the #Home anchor. It enhances site navigation and provides a more intuitive user experience.
Changes made:
Wrapped the header content in an <a> tag pointing to #Home.
Impact:
Improves navigation functionality.
Does not introduce significant visual changes.
> feat: add navigation to #home in header component
