midudev/jsconf.es

src/pages/index.astro
1. The KeepCoding link now works properly.
2. All accessibility issues were fixed.
> **Note: Only the `href` attributes are missing. I didn't add those because #5 fixes it.**
=> Fix sponsor link and accessibility issues

src/pages/index.astro
1. The text alignment in the Speakers section was fixed:
Before:
After:
2. The names of both speakers now show feedback (underline) when hover:
Before:
After:
=> Fix text center and link hover feedback

src/pages/index.astro
I have added the links to the GitHub profiles of the speakers since there was only a “#” as url.
=> Adding GitHub links of the speakers

src/sections/WhenAndWhere.astro
Four lines of code were modified to:
- Add flex-col to the 'When' and 'Where' articles
- Add horizontal padding to the entire section to match the rest of the website
- Set the maximum width of the articles
Before:
Now:
=> fix: Making 'Where' and 'When' articles responsive.

src/sections/Why.astro
En pantallas pequeñas el svg forzaba que la anchura fuese más grande
Solucionado ocultando el svg en pantallas pequeñas
=> style: Hide SVG on smaller screens for improved responsiveness

src/sections/Why.astro
Se ha corregido un problema de superposición en la sección "Why" donde un `div` con posición `absolute` esta cubriendo otros elementos, incluyendo (dependiendo de la resolución) el botón "¡Consigue tu entrada!". Para solucionar esto, se ha ajustado el `z-index` del `div` y del contenedor principal. Ahora, el `div` con el SVG tiene un `z-index` menor, asegurando que los elementos importantes, como el botón, se muestren correctamente por encima.
=> geekhadev - fix: enhance z-index for overlapping elements in Why section

src/components/UnderlineWord.astro, src/sections/Presenter.astro, src/sections/WhenAndWhere.astro
Arreglo en la posicion del underline en la vista mobile, antes los underline salian del marco con el cambio de posicion en las letras que tienen el underline y hacia que se viera un marco a la derecha de la web
Antes:
Despues:
=> style: Fix underline responsive

public/jsconfes.ics, src/sections/Agenda.astro
Cambiado el evento de Google Calendar por un archivo ICS para soportar todas las aplicaciones de calendario.
Resultado del ICS:
=> feat: add ICS file to support all calendar managers

src/sections/RunAndFun.astro
Ajuste del max-width para evitar el desbordamiento de la imagen principal en la seccion de la carrera en la version desktop
Antes:
Despues:
=> fix: adjust image width for better responsiveness

src/components/AddToCalendarDialog.astro
La sección difuminada de abajo estaba por encima del componente y al hacer hover éste se cerraba.
Tambien redondeé los bordes inferiores
https://github.com/user-attachments/assets/69780211-c63c-4cbb-9c93-ec25a038701f
=> fix: hover over "Agregalo a tu calendario"

src/sections/Footer.astro
Se agregó `rel="noopener noreferrer"`al enlace para mitigar riesgos de seguridad.
Evitar que las nuevas pestañas accedan a `window.opener`, lo que podría permitir ataques de tipo phising o manipulación de la página original.
- Añadí el atributo `noreferrer` al enlace.
- Verifiqué manualmente el enlace afectado.
- No se rompió ningún comportamiento existente.
=> Fix: add rel='noreferrer' to target='_blank' link

src/components/SpeakerCard.astro
Uso de aspect ratio en las imagenes de los speakers para que las imagenes guarden su lugar al cargar la pagina
Antes:
https://github.com/user-attachments/assets/9f0358ad-935a-4727-839f-fb23c0ecb7d2
Despues:
https://github.com/user-attachments/assets/81ded022-0b6a-44a4-a316-a0fa052d3dd4
=> Style: Add aspect ratio to speaker image for improved layout consistency

public/css/tito-widget.css, src/components/LinkEntrada.astro, src/layouts/Layout.astro
Se añade el botón embebido de tito para pagar directamente desde la página.
He logrado modificar algo el modal para que siga la temática:
Para ello he seguido la guía de tito: https://ti.to/docs/api/widget#tito-widget-v2-basic-usage
He deshabilitado que importe el css del widget y creado yo un fichero css en el que están todas las clases necesarias del fichero que ya no se importa. Esto me ha permitido editar ahí las clases para modificar la apariencia.
Las modificaciones son muy limitadas, así q he hecho lo que se ha podido.
Versión anterior:
@midudev revisa la integración por favor por si he hecho algo mal :)
=> Feat: tito setup and modal

src/sections/Header.astro
Se borraron las clases `h-screen` (div contenedor del nav) y `mt-auto` (nav) para resolver el problema de visibilidad en la versión móvil. Además, se añadió una altura del 100% al nav.
Resolver el problema de visibilidad de los botones en la versión móvil.
- Borrar la clase `h-screen` del componente padre del nav.
- Borrar la clase `mt-auto`del nav.
- Añadir la clase `h-full`al nav.
- Verificar manualmente en móvil.
- No afectó a la versión de escritorio.
| Before  | Now |
| ------------- | ------------- |
| ![Screenshot_20241218_095317_Chrome](https://github.com/user-attachments/assets/8f3f76fc-751a-42c3-a6bf-11d906a42a50)  | ![Screenshot_20241218_095404_Chrome](https://github.com/user-attachments/assets/2fddd256-0b5c-4091-9ff2-620d94375099)  |
=> Fix: delete unnecesary classes and add nav height

src/components/SpeakerCard.astro
=> fix: speakers card now have same height in small screens

src/components/Container.astro, src/components/Hero.astro, src/components/SpeakerCard.astro, src/sections/Agenda.astro, src/sections/Footer.astro, src/sections/PreEvent.astro, src/sections/Presenter.astro, src/sections/Speakers.astro, src/sections/Why.astro, src/sections/Workshops.astro, tailwind.config.mjs
- Extendí la config de tailwind para agregar una clase "container" que le da un max-w a las secciones que lo utilizan en el figma.
- Corregí el gradiente en el titulo principal
- La seccion Why tenía un scroll horizontal y no entraba bien en ciertos tamaños de pantalla
- Los Speakers no entraban bien en 1024px, bajé el grid a 3 y modifiqué el marginTop para que tenga distintos comportamientos en lg y en xl. 
- Corregí el titulo de Workshops.astro, con un text-balance y el ancho del texto "Programa del evento" para que quede como en el figma.
=> feat: container class and some tweaks

src/components/SpeakerCard.astro
En la feature olvidé indicar el min-width y estaba afectando tamaños menores a LG. 
Corregido y testeado
=> fix: min-width in speakers section

src/components/SpeakerCard.astro
Este PR habilita la selección de texto (`user-select: text`) en las tarjetas de los speakers (`src/components/SpeakerCard.astro`), permitiendo a los usuarios copiar información como nombres fácilmente. Este cambio mejora la experiencia de usuario al hacer más funcional y accesible la interacción con la información mostrada.
- Modificación en `src/components/SpeakerCard.astro` para incluir la propiedad `user-select: text`.
=> feat: enable user-select for speaker cards

src/components/Hero.astro
Esta PR endereza el enmarcado "exclusiva" para móviles:
| Antes | Después |
|---|---|
| ![Screenshot_20241229-172807](https://github.com/user-attachments/assets/35885e2d-9d93-45f5-8ac8-42b3b0c94a48) | ![Screenshot_20241229-172834](https://github.com/user-attachments/assets/e638d7dd-32fa-41b6-b24c-a1d2701fc8cf) |
=> fix: "exclusiva" in hero subtitle

src/sections/Header.astro
Esta PR corrige los márgenes del **brand** para móviles:
| Antes | Después |
|---|---|
| ![Screenshot_20241229-173059](https://github.com/user-attachments/assets/b599a1c3-21db-453e-bca6-96dab86f5d02) | ![Screenshot_20241229-173137](https://github.com/user-attachments/assets/976efc27-0004-4020-a55b-01fbe215cbff) |
=> fix: header brand in mobile

src/components/SpeakerCard.astro, src/sections/Speakers.astro
Esta PR deja las tarjetas de los **speakers** en **una sola columna para móviles** hasta `sm` en Tailwind.
Esto hace mejorar la legibilidad en los títulos y las descripciones.
| Antes | Después |
|---|---|
| ![Screenshot_20241229-172907](https://github.com/user-attachments/assets/1f2d033b-fc6e-40ee-a217-a0dbef084bbb) | ![Screenshot_20241229-173022](https://github.com/user-attachments/assets/ee9a70c1-dbea-491d-915a-fc421bf4baf4) |
=> fix: readability for mobile in speakers section

src/sections/Footer.astro
Esta PR corrige los márgenes del **brand** en el **footer** para móviles:
| Antes | Después |
|---|---|
| ![Screenshot_20241229-204921](https://github.com/user-attachments/assets/0a14eafa-0261-4839-93ee-9687a36e2e5f) | ![Screenshot_20241229-204941](https://github.com/user-attachments/assets/2fd63719-6872-4464-9eb7-befa8c2b8a9d) |
=> fix: footer brand in mobile

src/sections/Sponsors.astro
- Cambia el breakpoint de `md` a `lg` para mejorar el layout en pantallas medianas.
- Añade `gap-6 lg:gap-12` para mejorar el espacio entre la imagen y el texto.
- Añade `whitespace-nowrap` para evitar el rompimiento de línea en el texto.
- Añade `aria-label` para mejorar la accesibilidad.
Durante la revisión del componente, noté que el degradado del logo de KeepCoding genera un contraste negativo cuando el fondo cambia a blanco durante el hover. Esto puede afectar la legibilidad y la experiencia de usuario.
Sugiero evaluar la posibilidad de ajustar el color del texto o el degradado del logo para mejorar el contraste en este estado. No incluí este cambio en mi rama porque desconozco si es viable modificar el logo de KeepCoding, pero estaría encantado de implementarlo si se considera …
=> fix: enhance sponsor section layout and accessibility

src/sections/WhenAndWhere.astro, src/sections/Why.astro
Standardizing spacing in WhenAndWhere component elements
Previous:
Current:
Nota: es un pequeño cambio pero para mantener los espaciados estandares.
=> geekhadev - refactor: standardizing spacing in WhenAndWhere and Why components
